[package]
name = "rdl"
version = "0.2.2"
authors = ["nm <mnkisala@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/mnkisala/rdl"
description = "dmenu launcher for .desktop files"
readme = "README.md"

[dependencies]
clap = "2.33"
itertools = "0.10"
yaml-rust = "0.4"
